import Link from "next/link";
import { ArrowRight, ArrowUpRight, Bike, CircleCheck, Compass, GitCompareArrows, Search, ShieldCheck, Wrench } from "lucide-react";
import SiteShell from "@/components/site-shell";

const bikeTypes = [{ name: "Route", kind: "route", note: "Rapide & léger" }, { name: "VTT", kind: "mtb", note: "Trail & montagne" }, { name: "Gravel", kind: "gravel", note: "Entre deux terrains" }, { name: "CLM", kind: "clm", note: "Contre-la-montre" }, { name: "Ville", kind: "ville", note: "Trajets quotidiens" }];

export default function Home() {
  return <SiteShell><main><section className="home-hero"><div className="home-hero-copy"><span className="eyebrow"><i /> LE GUIDE VISUEL DU MONTAGE VÉLO</span><h1>Chaque pièce<br />à sa <em>bonne place.</em></h1><p>Décrivez votre vélo, explorez ses composants et vérifiez les standards avant de construire ou de faire évoluer votre montage.</p><div className="hero-actions"><Link className="button button-lime" href="/atelier">Choisir mon vélo <ArrowRight size={17} /></Link><Link className="button button-outline" href="/composants">Explorer les composants <ArrowUpRight size={16} /></Link></div><div className="hero-trust"><span><ShieldCheck size={16} /> Sources visibles</span><span><CircleCheck size={16} /> Compatibilités nuancées</span></div></div><div className="hero-scene"><div className="scene-label"><span>ATELIER VELOSCOPE</span><span>01 / 04</span></div><div className="scene-glow"/><div className="scene-bike" aria-label="Illustration stylisée d’un vélo de route"><div className="scene-wheel rear"/><div className="scene-wheel front"/><svg viewBox="0 0 600 340" aria-hidden="true"><g fill="none" stroke="#e7ebdc" strokeWidth="7" strokeLinejoin="round" strokeLinecap="round"><path d="M134 236 246 236 340 118 246 236 198 112 134 236M246 236 416 236 340 118M416 236 454 116M324 104h53M198 112l-24-14M190 96h23M454 116l17-13"/><path d="m238 228 14 16m71-131-18-15" stroke="#cefa6e" strokeWidth="5"/></g><g fill="#cefa6e"><circle cx="246" cy="236" r="10"/><circle cx="340" cy="118" r="7"/></g><path d="M246 236 277 200l-31 36m-2 0 32 34m-31-34-30 5" stroke="#cefa6e" strokeWidth="4" fill="none" strokeLinecap="round"/></svg><div className="scene-callout callout-frame"><span className="callout-line"/><span>CADRE <b>taille · axe · boîtier</b></span></div><div className="scene-callout callout-wheel"><span className="callout-line"/><span>ROUE <b>diamètre · moyeu · corps</b></span></div><div className="scene-sticker"><Bike size={16}/><span>UN VÉLO<br/><b>VOTRE MONTAGE</b></span></div><div className="scene-caption">ILLUSTRATION DE PRINCIPE · LES IMAGES DU PROJET SERONT INTÉGRÉES AU CONFIGURATEUR</div></div></div></section>
    <section className="home-statbar"><div><strong>8 846</strong><span>fiches de composants importées</span></div><div><strong>43</strong><span>marques dans la bibliothèque</span></div><div><strong>23</strong><span>types de composants</span></div><Link href="/composants">Parcourir la bibliothèque <ArrowRight size={16}/></Link></section>
    <section className="bike-picker content-wrap"><div className="section-kicker">COMMENCER PAR VOTRE PRATIQUE <span>01 — 04</span></div><div className="section-title-row"><div><h2>Quel vélo avez-vous en tête ?</h2><p>Choisissez une base. Vous pourrez ensuite décrire le montage pièce par pièce.</p></div><Link href="/atelier" className="text-link">Ouvrir le configurateur <ArrowUpRight size={16}/></Link></div><div className="bike-type-grid">{bikeTypes.map((bike,index)=><Link href={`/atelier?type=${bike.kind}`} key={bike.kind} className={`bike-type-card type-${bike.kind}`}><span className="type-index">0{index+1}</span><span className="type-graphic"><Bike size={50} strokeWidth={1.15}/></span><span className="type-name">{bike.name}<small>{bike.note}</small></span><ArrowUpRight className="type-arrow" size={18}/></Link>)}</div></section>
    <section className="home-paths"><div className="content-wrap"><div className="section-kicker">DU PREMIER CHOIX À LA DERNIÈRE VIS <span>02 — 04</span></div><div className="path-grid"><Link href="/atelier" className="path-card path-dark"><span className="path-icon"><Wrench size={20}/></span><span className="path-step">CONFIGURER</span><h3>Visualisez votre vélo.</h3><p>Une vue graphique ou une liste détaillée des composants, selon votre façon de travailler.</p><span className="path-link">Démarrer un montage <ArrowRight size={16}/></span><span className="path-ghost">01</span></Link><Link href="/composants" className="path-card path-light"><span className="path-icon"><Search size={20}/></span><span className="path-step">RECHERCHER</span><h3>Trouvez la bonne référence.</h3><p>Filtrez les composants par type, marque et caractéristiques documentées.</p><span className="path-link">Parcourir les pièces <ArrowRight size={16}/></span><span className="path-ghost">02</span></Link><Link href="/comparateur" className="path-card path-accent"><span className="path-icon"><GitCompareArrows size={20}/></span><span className="path-step">COMPARER</span><h3>Choisissez en connaissance.</h3><p>Mettez des pièces côte à côte et suivez le budget de votre projet.</p><span className="path-link">Ouvrir le comparateur <ArrowRight size={16}/></span><span className="path-ghost">03</span></Link></div></div></section>
    <section className="confidence-band content-wrap"><div className="confidence-mark"><Compass size={29}/></div><div><span className="eyebrow"><i/> LA COMPATIBILITÉ DÉPEND DU MONTAGE</span><h2>Chaque réponse montre ses sources.</h2><p>Les dimensions présentes dans le fichier sont affichées comme elles ont été fournies. Une fiche sans mesure ni source reste à vérifier.</p></div><Link href="/contribuer" className="button button-dark">Améliorer une fiche <ArrowUpRight size={15}/></Link></section>
    </main></SiteShell>;
}


