"use client";

import { useEffect, useMemo, useState } from "react";
import { ArrowRightLeft, Search, X } from "lucide-react";
type Part = { id: string; brand: string; model: string; category: string; lifespan_km: string | number; name: string };
const labels: Record<string,string> = { tyre:"Pneu",wheel:"Roue",fork:"Fourche",chainrings:"Plateau",cassette:"Cassette",chain:"Chaîne",pedals:"Pédales","brake-rotor":"Disque de frein","brake-pads":"Plaquettes",shock:"Amortisseur","seat-post":"Tige de selle","bottom-bracket":"Boîtier de pédalier",brake:"Frein",cranks:"Manivelle",battery:"Batterie" };
export default function ComparisonBuilder(){
  const [query,setQuery]=useState("");
  const [items,setItems]=useState<Part[]>([]);
  const [parts,setParts]=useState<Part[]>([]);
  useEffect(()=>{fetch("/data/component-library.json").then(response=>response.json()).then((data:Part[])=>setParts(data)).catch(()=>setParts([]));},[]);
  const suggestions=useMemo(()=>parts.filter(part=>`${part.name} ${part.brand} ${part.model}`.toLocaleLowerCase("fr").includes(query.toLocaleLowerCase("fr").trim())&&!items.some(item=>item.id===part.id)).slice(0,7),[parts,query,items]);
  return <div className="compare-builder"><div className="compare-search"><Search size={17}/><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Rechercher une pièce à comparer…" aria-label="Rechercher une pièce à comparer"/></div>{query&&<div className="compare-suggestions">{suggestions.map(part=><button key={part.id} onClick={()=>{setItems(current=>[...current,part].slice(0,4));setQuery("");}}><span><b>{part.name}</b><small>{part.brand} · {labels[part.category]??part.category}</small></span><ArrowRightLeft size={15}/></button>)}</div>}<div className="compare-table-wrap"><table className="compare-table"><thead><tr><th>Caractéristique</th>{items.map((item,index)=><th key={item.id}><span>OPTION 0{index+1}</span><button onClick={()=>setItems(current=>current.filter(part=>part.id!==item.id))} aria-label={`Retirer ${item.name}`}><X size={14}/></button></th>)}{items.length<2&&<th className="compare-empty-head">AJOUTER UNE PIÈCE</th>}</tr></thead><tbody><tr><th>Pièce</th>{items.map(item=><td key={item.id}><b>{item.name}</b></td>)}{items.length<2&&<td>Utilisez la recherche ci-dessus</td>}</tr><tr><th>Marque</th>{items.map(item=><td key={item.id}>{item.brand}</td>)}{items.length<2&&<td>—</td>}</tr><tr><th>Modèle</th>{items.map(item=><td key={item.id}>{item.model}</td>)}{items.length<2&&<td>—</td>}</tr><tr><th>Famille</th>{items.map(item=><td key={item.id}>{labels[item.category]??item.category}</td>)}{items.length<2&&<td>—</td>}</tr><tr><th>Durée indicative</th>{items.map(item=><td key={item.id}>{Number(item.lifespan_km)>0?`${Number(item.lifespan_km).toLocaleString("fr-FR")} km`:"Non renseignée"}</td>)}{items.length<2&&<td>—</td>}</tr><tr><th>Prix</th>{items.map(item=><td key={item.id}>Non disponible dans la source</td>)}{items.length<2&&<td>—</td>}</tr><tr><th>Compatibilité</th>{items.map(item=><td key={item.id}><span className="confidence confidence-low">À documenter</span></td>)}{items.length<2&&<td>—</td>}</tr></tbody></table></div><div className="compare-footnote">Maximum 4 pièces. Les champs affichés correspondent aux données présentes; aucun prix ou résultat de compatibilité n’est fabriqué.</div></div>
}

